Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20200831192720_devise_create_users.rb
db/schema.rb
test/models/user_test.rb

installing device and creating user model

---

app/models/company.rb
app/models/user.rb
db/migrate/20200901135825_create_companies.rb
db/schema.rb
test/models/company_test.rb

Created  company model with validations

Created Company Model

---

db/migrate/20200901161206_change_price_type_to_integer.rb
db/schema.rb

Altered the price from float to integer

Changed Price of Products from float to integer

---

app/models/shopping_cart.rb
app/models/user.rb
db/migrate/20200901141820_create_shopping_carts.rb
db/migrate/20200901161523_change_price_to_be_integer.rb
db/schema.rb
test/models/shopping_cart_test.rb

Criei o modelo do shopping cart já testado no console com a dependência do usuário. Todas as validações também já testadas.

ShoppingCart model Create

---

app/models/booking.rb
app/models/product.rb
app/models/shopping_cart.rb
db/migrate/20200901173538_create_bookings.rb
db/schema.rb
test/models/booking_test.rb

Created booking model

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/companies_controller.rb
app/controllers/pages_controller.rb
app/policies/application_policy.rb
app/policies/company_policy.rb
app/views/layouts/application.html.erb
test/policies/company_policy_test.rb

installed pundit and tested with company model

---

Gemfile
Gemfile.lock
app/controllers/products_controller.rb
app/views/products/create.html.erb
app/views/products/destroy.html.erb
app/views/products/edit.html.erb
app/views/products/index.html.erb
app/views/products/new.html.erb
app/views/products/show.html.erb
app/views/products/update.html.erb
config/routes.rb
db/seeds.rb
test/controllers/products_controller_test.rb

Cara era prra criar o product CRUS mas só criei o Seed file

Era pra ser o CRUD de products mas virou só o seed file

---

app/models/booking.rb
app/models/company.rb
app/models/product.rb
app/models/user.rb
db/seeds.rb

Fixed seed issues

---

app/assets/stylesheets/application.scss
app/controllers/application_controller.rb
app/controllers/products_controller.rb
app/views/products/index.html.erb

Created the view of the products index

Created the index view

---

app/views/layouts/application.html.erb

Linked product index to home page

linked the product index to the home page

---

app/controllers/products_controller.rb
app/policies/product_policy.rb
app/views/products/edit.html.erb
test/policies/product_policy_test.rb

Criei o edit do products com policies

Create edit product

---

app/controllers/products_controller.rb
app/models/user.rb
app/policies/product_policy.rb
app/views/products/create.html.erb
app/views/products/new.html.erb
test/policies/product_policy_test.rb

Please, take a look at the code. I tested here and apparently, its working.

Create a product

---

app/controllers/products_controller.rb
app/models/user.rb
app/policies/product_policy.rb
app/views/products/my_index.html.erb
config/routes.rb

Terminada a funcionalidade de deleter produto pelo user responsável por ele

Create destroy product

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_map.scss
app/views/layouts/application.html.erb
app/views/products/index.html.erb

Criei uma view da index.html.erb com CSS

Front-End da View Index sem cloudinary e geolocation

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_map.scss
app/views/layouts/application.html.erb
app/views/products/index.html.erb

Inseri o link em cada produto na INDEX.html

Link to index html

---

Gemfile
Gemfile.lock
app/views/companies/show.html.erb
app/views/layouts/application.html.erb

Implemented the links to create a company, create a product, and generated a list of products for each company in the companies/show.html.erb. Please, check if its ok. No front end implemented yet

creating links for better user experience

---

app/controllers/products_controller.rb
app/models/product.rb
app/models/shopping_cart.rb
app/models/user.rb
app/views/products/edit.html.erb
app/views/products/new.html.erb
app/views/products/show.html.erb
db/migrate/20200902151844_add_description_to_companies.rb
db/migrate/20200902152133_delet_description_to_companies.rb
db/migrate/20200902152257_add_description_to_products.rb
db/schema.rb
db/seeds.rb

Added description to products table, and changed the seeds

Description to companies

---

db/schema.rb
db/seeds.rb

Coloquei os endereços para marcação no geocoder mas com algumas falhas de localização do LAT LONG pela GEM

Improve seed file

---

app/controllers/application_controller.rb
app/views/devise/registrations/edit.html.erb

Improved edit form

---

app/views/products/index.html.erb
app/views/products/show.html.erb

Solved the cloudinary issue with the if

solved cloudinary foto issue

---

app/controllers/products_controller.rb
app/views/companies/show.html.erb

Created a button for editing and another for deleting the tours

added edit and delete button for products

---

app/controllers/products_controller.rb

The site only shows active boat tours now

Filtered the active boats in index

---

app/javascript/packs/application.js
app/javascript/plugins/init_autocomplete.js
app/views/companies/new.html.erb
app/views/devise/registrations/new.html.erb
package.json
yarn.lock

Feature de autocomplete de Adress pronta e validada

Address autocomplete

---

app/views/products/index.html.erb

Improved the index of products

Added the company name to the product index and translated to english

---

app/assets/stylesheets/components/_cards.scss
app/views/products/show.html.erb
app/views/shopping_carts/index.html.erb
app/views/shopping_carts/show.html.erb

Working on some css details. I think there will be a few conflicts

Css continued

---

app/views/shopping_carts/show.html.erb

Criei cartões para diferentes itens no shopping cart

Criei card para as os itens no shopping cart

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/top_products.scss
app/controllers/pages_controller.rb
app/views/pages/home.html.erb

Added some products cards to the home page

added products cards to home page
